In [1]:
import numpy as np

## Sigmoid functions

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1 - x)

## Output/Input data, Synaptic weights

In [4]:
inp = [[0, 0, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 1]]

out = [[1, 1, 0, 1]]

training_inputs = np.array(inp)
training_outputs = np.array(out).T
outputs = []

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [10]:
print("Synaptic Weights: ")
print(synaptic_weights)

Synaptic Weights: 
[[-4.62053753]
 [ 4.02589431]
 [ 5.60578902]]


## Training

In [6]:
number_of_epoch = 10000

In [7]:
for i in range(10000):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    errors = training_outputs - outputs
    adjustments = errors * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [8]:
print("Synaptic weights after training: ")
print(synaptic_weights)

Synaptic weights after training: 
[[-4.62053753]
 [ 4.02589431]
 [ 5.60578902]]


In [9]:
print("Outputs: ")
print(outputs)

Outputs: 
[[0.99633674]
 [0.99338051]
 [0.00975196]
 [0.99993438]]
