In [12]:
import numpy as np

## Sigmoid functions

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1 - x)

## Output/Input data, Synaptic weights

In [14]:
inp = [[0, 0, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 1]]

out = [[1, 1, 0, 1]]

training_inputs = np.array(inp)
training_outputs = np.array(out).T
outputs = []

np.random.seed(1)

synaptic_weights = 2 * np.random.random((3, 1)) - 1

In [15]:
print("Synaptic Weights: ")
print(synaptic_weights)

Synaptic Weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


## Training

In [16]:
number_of_epoch = 10000

In [17]:
for i in range(number_of_epoch):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    errors = training_outputs - outputs
    adjustments = errors * sigmoid_derivative(outputs)
    synaptic_weights += np.dot(input_layer.T, adjustments)

In [18]:
print("Synaptic weights after training: ")
print(synaptic_weights)

Synaptic weights after training: 
[[-4.62053753]
 [ 4.02589431]
 [ 5.60578902]]


In [19]:
print("Outputs: ")
print(outputs)

Outputs: 
[[0.99633674]
 [0.99338051]
 [0.00975196]
 [0.99993438]]


## Creating our own neural network class

In [27]:
import numpy as np
class NeuralNetwork:
    def __init__(self):
        np.random.seed(1)
        self.synaptic_weights  = 2 * np.random.random((3,1)) - 1
        
        
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    
    def sigmoid_derivative(self, x):
        return x * (1 - x)
    
    
    def train(self, training_inputs, training_outputs, n_epoch):
        for i in range(n_epoch):
            output = self.fit(training_inputs)
            error = training_outputs - output
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))
            self.synaptic_weights += adjustments
            
            
    def fit(self, inputs):
        inputs = inputs.astype(float)
        return self.sigmoid(np.dot(inputs, self.synaptic_weights))

In [28]:
net = NeuralNetwork()
print('Synaptic weights before taining: ')
print(net.synaptic_weights)

Synaptic weights before taining: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [37]:
inp = [[0, 0, 1],
       [1, 1, 1],
       [1, 0, 0],
       [0, 1, 1]]

out = [[1, 1, 0, 1]]

training_inputs = np.array(inp)
training_outputs = np.array(out).T

net.train(training_inputs, training_outputs, 10000)

In [38]:
print('Synaptic weights after taining: ')
print(net.synaptic_weights)

Synaptic weights after taining: 
[[-5.52270839]
 [ 4.81477511]
 [ 6.60990548]]


In [36]:
test_data = np.array([input("Test data: ").split()])
print('Your Input data is: ' + str(test_data))

Test data:  0 1 0


Your Input data is: [['0' '1' '0']]


In [39]:
print(net.fit(test_data))

[[0.99195618]]
